# Generated by Django 5.2.12 on 2026-03-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='pages',
        ),
        migrations.AddField(
            model_name='chapter',
            name='page_keys',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of S3 object keys for chapter pages.'),
        ),
    ]
