# Generated by Django 5.2.12 on 2026-03-22 17:34

import comics.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_remove_chapter_pages_chapter_page_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='comic',
            name='banner',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='comic',
            name='cover',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='ComicUploadDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scope_prefix', models.CharField(max_length=500, unique=True)),
                ('cover', models.CharField(blank=True, max_length=500)),
                ('banner', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Ожидает завершения'), ('completed', 'Завершён'), ('expired', 'Истёк'), ('cancelled', 'Отменён')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(default=comics.models.default_draft_expiration)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_upload_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChapterUploadDraft',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('chapter_number', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_page_count', models.PositiveIntegerField(default=0)),
                ('scope_prefix', models.CharField(max_length=500, unique=True)),
                ('page_keys', models.JSONField(blank=True, default=list, help_text='Ordered list of S3 object keys uploaded for chapter draft pages.')),
                ('status', models.CharField(choices=[('pending', 'Ожидает завершения'), ('completed', 'Завершён'), ('expired', 'Истёк'), ('cancelled', 'Отменён')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(default=comics.models.default_draft_expiration)),
                ('comic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_upload_drafts', to='comics.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_upload_drafts', to=settings.AUTH_USER_MODEL)),
                ('comic_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_upload_drafts', to='comics.comicuploaddraft')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('comic__isnull', False), ('comic_draft__isnull', True)), models.Q(('comic__isnull', True), ('comic_draft__isnull', False)), _connector='OR'), name='chapter_upload_draft_has_single_parent')],
            },
        ),
    ]
