# Generated by Django 5.2.12 on 2026-03-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_remove_comic_cover_image_comic_banner_comic_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicuploaddraft',
            name='tag_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
