# Generated by Django 5.2.12 on 2026-04-05 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_genre_description_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='comicuploaddraft',
            name='genre_ids',
        ),
        migrations.AddField(
            model_name='comic',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comics', to='comics.genre'),
        ),
        migrations.AddField(
            model_name='comicuploaddraft',
            name='genre_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
