# Generated by Django 5.2.12 on 2026-04-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0010_comicreadingprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('under_review', 'На модерации'), ('published', 'Опубликован'), ('blocked', 'Заблокирован'), ('revision', 'На доработке')], default='draft', max_length=32),
        ),
    ]
