# Generated by Django 5.2.12 on 2026-05-30 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0012_comic_moderation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comic',
            index=models.Index(fields=['status', 'published_at', 'created_at'], name='comic_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='comic',
            index=models.Index(fields=['author', 'updated_at', 'created_at'], name='comic_author_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='comicreadingprogress',
            index=models.Index(fields=['user', 'updated_at', 'created_at'], name='comic_prog_user_idx'),
        ),
    ]
