# Generated by Django 5.2.12 on 2026-06-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0014_comic_has_published_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('chapter_number', 'id'), 'verbose_name': 'глава', 'verbose_name_plural': 'главы'},
        ),
        migrations.AlterModelOptions(
            name='chapteruploaddraft',
            options={'ordering': ('-created_at',), 'verbose_name': 'черновик загрузки главы', 'verbose_name_plural': 'черновики загрузки глав'},
        ),
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ('-created_at',), 'verbose_name': 'комикс', 'verbose_name_plural': 'комиксы'},
        ),
        migrations.AlterModelOptions(
            name='comicrating',
            options={'verbose_name': 'оценка комикса', 'verbose_name_plural': 'оценки комиксов'},
        ),
        migrations.AlterModelOptions(
            name='comicreadingprogress',
            options={'verbose_name': 'прогресс чтения комикса', 'verbose_name_plural': 'прогресс чтения комиксов'},
        ),
        migrations.AlterModelOptions(
            name='comicstats',
            options={'verbose_name': 'статистика комикса', 'verbose_name_plural': 'статистика комиксов'},
        ),
        migrations.AlterModelOptions(
            name='comicuploaddraft',
            options={'ordering': ('-created_at',), 'verbose_name': 'черновик загрузки комикса', 'verbose_name_plural': 'черновики загрузки комиксов'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'тег комикса', 'verbose_name_plural': 'теги комиксов'},
        ),
    ]
