# Generated by Django 5.2.12 on 2026-06-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0015_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
