[pytest]
DJANGO_SETTINGS_MODULE = core.test_settings
python_files = tests.py test_*.py *_tests.py
addopts = -ra
norecursedirs = venv .venv __pycache__
testpaths =
    analytics
    authentication
    blog
    comics
    interactions
    users
