# Generated by Django 5.2.12 on 2026-05-29 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_owner_i_3ce1e3_idx',
            old_name='analytics_o_created_b8cb92_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_owner_i_26dc74_idx',
            old_name='analytics_o_content_3af68e_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_owner_i_96d214_idx',
            old_name='analytics_o_event_t_6501b2_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_content_440e13_idx',
            old_name='analytics_c_object__e9e521_idx',
        ),
    ]
