# Generated by Django 5.2.12 on 2026-06-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_uniquecontentview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticsevent',
            options={'ordering': ('-created_at',), 'verbose_name': 'событие аналитики', 'verbose_name_plural': 'события аналитики'},
        ),
        migrations.AlterModelOptions(
            name='uniquecontentview',
            options={'ordering': ('-last_viewed_at', '-first_viewed_at'), 'verbose_name': 'уникальный просмотр контента', 'verbose_name_plural': 'уникальные просмотры контента'},
        ),
    ]
