# Generated by Django 5.2.12 on 2026-04-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='age_rating',
            field=models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='16+', max_length=4),
        ),
    ]
