# Generated by Django 5.2.12 on 2026-05-30 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_moderation_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'published_at', 'updated_at', 'created_at'], name='post_status_pub_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'updated_at', 'created_at'], name='post_author_upd_idx'),
        ),
    ]
