# Generated by Django 5.2.12 on 2026-06-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_post_status_pub_idx_post_post_author_upd_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtag',
            options={'ordering': ('name',), 'verbose_name': 'тег блога', 'verbose_name_plural': 'теги блога'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'пост блога', 'verbose_name_plural': 'посты блога'},
        ),
        migrations.AlterModelOptions(
            name='postuploaddraft',
            options={'ordering': ('-created_at',), 'verbose_name': 'черновик загрузки поста', 'verbose_name_plural': 'черновики загрузки постов'},
        ),
    ]
