# Generated by Django 5.2.12 on 2026-06-02 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0014_comic_has_published_updates'),
        ('users', '0003_alter_user_avatar_avataruploaddraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters_read_count', models.PositiveIntegerField(default=0)),
                ('comics_started_count', models.PositiveIntegerField(default=0)),
                ('comics_finished_count', models.PositiveIntegerField(default=0)),
                ('favorite_comics_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('reading_streak_days', models.PositiveIntegerField(default=0)),
                ('longest_reading_streak_days', models.PositiveIntegerField(default=0)),
                ('published_comics_count', models.PositiveIntegerField(default=0)),
                ('published_chapters_count', models.PositiveIntegerField(default=0)),
                ('last_reading_activity_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-awarded_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'code'), name='unique_achievement_per_user')],
            },
        ),
        migrations.CreateModel(
            name='UserFinishedComic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_by_users', to='comics.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_comics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'comic'), name='unique_finished_comic_per_user')],
            },
        ),
        migrations.CreateModel(
            name='UserReadChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_links', to='comics.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_chapters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('user', 'chapter'), name='unique_read_chapter_per_user')],
            },
        ),
        migrations.CreateModel(
            name='UserReadingActivityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_activity_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-activity_date', '-id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'activity_date'), name='unique_reading_activity_day_per_user')],
            },
        ),
    ]
