# Generated by Django 5.2.12 on 2026-06-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_monthlyrecap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avataruploaddraft',
            options={'ordering': ('-created_at',), 'verbose_name': 'черновик загрузки аватара', 'verbose_name_plural': 'черновики загрузки аватаров'},
        ),
        migrations.AlterModelOptions(
            name='monthlyrecap',
            options={'ordering': ('-year', '-month', '-generated_at'), 'verbose_name': 'ежемесячный итог', 'verbose_name_plural': 'ежемесячные итоги'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ('-awarded_at', '-id'), 'verbose_name': 'достижение пользователя', 'verbose_name_plural': 'достижения пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userfinishedcomic',
            options={'ordering': ('-created_at',), 'verbose_name': 'завершенный комикс', 'verbose_name_plural': 'завершенные комиксы'},
        ),
        migrations.AlterModelOptions(
            name='userfollow',
            options={'ordering': ('-created_at',), 'verbose_name': 'подписка пользователя', 'verbose_name_plural': 'подписки пользователей'},
        ),
        migrations.AlterModelOptions(
            name='userreadchapter',
            options={'ordering': ('-created_at',), 'verbose_name': 'прочитанная глава', 'verbose_name_plural': 'прочитанные главы'},
        ),
        migrations.AlterModelOptions(
            name='userreadingactivityday',
            options={'ordering': ('-activity_date', '-id'), 'verbose_name': 'день читательской активности', 'verbose_name_plural': 'дни читательской активности'},
        ),
        migrations.AlterModelOptions(
            name='userstats',
            options={'verbose_name': 'статистика пользователя', 'verbose_name_plural': 'статистика пользователей'},
        ),
    ]
