# Generated by Django 5.2.12 on 2026-05-30 20:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_post_status_pub_idx_post_post_author_upd_idx'),
        ('comics', '0013_comic_comic_status_pub_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0003_notification_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='interaction_content_7ff8b8_idx',
        ),
        migrations.AddIndex(
            model_name='comicfavorite',
            index=models.Index(fields=['user', 'created_at'], name='fav_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['content_type', 'object_id', 'created_at'], name='comment_target_created_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at', 'created_at'], name='notif_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='postreadinghistory',
            index=models.Index(fields=['user', 'updated_at', 'created_at'], name='post_hist_user_idx'),
        ),
    ]
