# Generated by Django 5.2.12 on 2026-06-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_contentreaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comicfavorite',
            options={'verbose_name': 'избранный комикс', 'verbose_name_plural': 'избранные комиксы'},
        ),
        migrations.AlterModelOptions(
            name='comiclike',
            options={'verbose_name': 'лайк комикса', 'verbose_name_plural': 'лайки комиксов'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='contentreaction',
            options={'verbose_name': 'реакция на контент', 'verbose_name_plural': 'реакции на контент'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('read_at', '-created_at'), 'verbose_name': 'уведомление', 'verbose_name_plural': 'уведомления'},
        ),
        migrations.AlterModelOptions(
            name='postreadinghistory',
            options={'ordering': ('-updated_at', '-created_at'), 'verbose_name': 'запись истории чтения поста', 'verbose_name_plural': 'история чтения постов'},
        ),
    ]
